<?php
$name = $_POST['username'];
$email = $_POST['email'];
$connection = mysqli_connect('localhost', 'Webshop_user', 'Webshop_password', 'webshop');

$compare_query = "SELECT * FROM USERS WHERE USERNAME = '$name' OR EMAIL = '$email'";

$result = mysqli_query($connection, $compare_query);


if(mysqli_num_rows($result) > 0)
    {
        header('location: ../modules/register.php?error=USERNAME_OR_EMAIL_ALREADY_TAKEN_ERROR');
        exit;
    }
$temppassword = 'p'.rand(0,9).rand(0,9).rand(0,9).rand(0,9).rand(0,9).rand(0,9);

$encrpassword = hash_init('sha512');
hash_update($encrpassword, $temppassword);
$finalpassword = hash_final($encrpassword);


use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader
require 'vendor/autoload.php';

//Create an instance; passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
    $mail->isSMTP();                                            //Send using SMTP.
    $mail->Host       = 'smtp.gmail.com';                     //Set the SMTP server to send through.
    //Note: SMTP server is different for each of email services. This one is for gmail emails. 
    //If we change the email we use, this should be kept in mind
    $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
    $mail->Username   = 'webshopmakula@gmail.com';                     //SMTP username
    //For gmail it matches the gmail adress

    $mail->Password   = 'wluvkfffpttetcqd';                               //SMTP password
    //This password is generated by creating a thing in gmail's "App passwords" tab. It can only be viewed once, when it's created. 
    //It's sufficient to gain access to the said email's account, and preferable should be secured. 

    $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
    $mail->Port       = 465;   //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

    //Recipients
    $mail->setFrom('webshopmakula@gmail.com', 'Makula'); //Here we
    //$mail->addAddress('joe@example.net', 'Joe User');     //Add a recipient
    $mail->addAddress($email);   
    //This is where we set the email we want to send to
    //We can add several adresses, by calling this function several times
    //Name is optional
    $mail->addReplyTo('webshopmakula@gmail.com', 'Information');
 
    //Attachments
    // $mail->addAttachment('/var/tmp/file.tar.gz');         //Add attachments
    // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    //Optional name

    //Content
    $mail->isHTML(true);                                  //Set email format to HTML
    $mail->Subject = 'Registration confirmation';
    $mail->Body    = 'Your password - '.$temppassword;
    $mail->AltBody = 'Your password - '.$temppassword;

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}

$insert_query = "INSERT INTO `users` (`USERNAME`, `ID`, `LAST_ONLINE`, `PASSWORD`, `CONFIRMATION_CODE`, `CURRENT_BASKET`, `EMAIL`)
VALUES ('$name', NULL, current_timestamp(), '$finalpassword', '', '', '$email')";

mysqli_query($connection, $insert_query);

header('location: ../modules/login.php?message=registered');

?>