<?php
//This is an example of a script that sends an email. Use it for reference, or create a separate function to make this easier

//Import PHPMailer classes into the global namespace
//These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader
require 'vendor/autoload.php';

//Create an instance; passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
    $mail->isSMTP();                                            //Send using SMTP.
    $mail->Host       = 'smtp.gmail.com';                     //Set the SMTP server to send through.
    //Note: SMTP server is different for each of email services. This one is for gmail emails. 
    //If we change the email we use, this should be kept in mind
    $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
    $mail->Username   = 'webshopmakula@gmail.com';                     //SMTP username
    //For gmail it matches the gmail adress

    $mail->Password   = 'wluvkfffpttetcqd';                               //SMTP password
    //This password is generated by creating a thing in gmail's "App passwords" tab. It can only be viewed once, when it's created. 
    //It's sufficient to gain access to the said email's account, and preferable should be secured. 

    $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
    $mail->Port       = 465;   //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

    //Recipients
    $mail->setFrom('webshopmakula@gmail.com', 'Makula'); //Here we
    //$mail->addAddress('joe@example.net', 'Joe User');     //Add a recipient
    $mail->addAddress('mykyta.kusmerchuk@student.reutlingen-university.de');   
    //This is where we set the email we want to send to
    //We can add several adresses, by calling this function several times
    //Name is optional
    $mail->addReplyTo('webshopmakula@gmail.com', 'Information');
 
    //Attachments
    // $mail->addAttachment('/var/tmp/file.tar.gz');         //Add attachments
    // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    //Optional name

    //Content
    $mail->isHTML(true);                                  //Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'If you can read this, then I have successfully figured out sending emails';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
//This entire script by itself outputs quite a lot of data to the page, so it shouldn't be opened as a page.